[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[plugins]]
  package = "@netlify/plugin-functions-install-core"