[build]
  command = "pip install --upgrade pip && pip install -r requirements.txt --no-cache-dir"
  publish = "public"  # Adjust to your output directory

[build.environment]
  PYTHON_VERSION = "3.10"
  PIP_NO_BINARY = "pandas"  # Force pandas to be compiled

[[plugins]]
  package = "@netlify/plugin-python"